baseURL = 'https://guilherme-salome.github.io/'
title = "Guilherme Salome"
languageCode = 'en'
theme = "blowfish"
mainSections = "blog"


[params]
  description = "Personal website of Guilherme Salome"
  author = { name = "Guilherme Salome", email = "guilhermesalome@gmail.com" }
  colorScheme = "guilherme"
  enableSearch = true
  smartTOC = true
  list.groupByYear = true
  article.showReadingTime = false
  article.showAuthor = false
  article.showDate = true
  article.showWordCount = false
  article.showTaxonomies = true
  homepage.layout = "hero"
  homepage.homepageImage = "hero.png"
  homepage.showRecent = true
  homepage.showRecentItems = 10
  homepage.cardView = true


[menu]
  [[menu.main]]
  name = "About"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

  [[menu.main]]
  name = "Consulting"
  url = "/consulting/"
  weight = 3

  [[menu.main]]
  name = "Resume"
  url = "/resume.pdf"
  weight = 4

  [[menu.main]]
  name = "Academic Work"
  url = "/academic-work/"
  weight = 5
